spring.main.banner-mode=off
spring.main.web-application-type=none
spring.threads.virtual.enabled=true

spring.ai.anthropic.api-key=${ANTHROPIC_API_KEY}
spring.ai.anthropic.chat.options.max-tokens=2000
spring.ai.anthropic.chat.options.model=claude-sonnet-5-5

spring.ai.typesafe.api-key=${TYPESAFE_API_KEY:}

spring.ai.inspector.enabled=true

# spring.ai.typesafe.base-url=http://localhost:11434
# spring.ai.typesafe.api-key=ollama
# spring.ai.typesafe.timeout=60s
# spring.ai.typesafe.retry.total-timeout=150s
# spring.ai.typesafe.model=tev1:0.8b
# spring.ai.typesafe.model=nimble

# spring.ai.typesafe.base-url=http://localhost:8009
# spring.ai.typesafe.model=kev-latest
# spring.ai.typesafe.api-key=local
# spring.ai.typesafe.timeout=60s
# spring.ai.typesafe.retry.total-timeout=150s