spring.main.banner-mode=off
spring.main.web-application-type=none
spring.threads.virtual.enabled=true

# spring.ai.anthropic.api-key=${ANTHROPIC_API_KEY}
# spring.ai.anthropic.chat.options.max-tokens=2000
# spring.ai.anthropic.chat.options.model=claude-sonnet-4-20250514

spring.ai.openai-sdk.api-key=${OPENAI_API_KEY}
spring.ai.openai-sdk.chat.options.model=gpt-5-mini-2025-08-07
spring.ai.openai-sdk.chat.options.temperature=1.0
