spring.main.banner-mode=off
spring.application.name=todo-demo
spring.main.web-application-type=none

spring.ai.anthropic.api-key=${ANTHROPIC_API_KEY}
spring.ai.anthropic.chat.options.model=claude-sonnet-4-5-20250929

spring.ai.openai-sdk.api-key=${OPENAI_API_KEY}
spring.ai.openai-sdk.chat.options.model=gpt-5-mini-2025-08-07
spring.ai.openai-sdk.chat.options.temperature=1.0

spring.ai.google.genai.project-id=${GOOGLE_CLOUD_PROJECT}
# spring.ai.google.genai.location=${GOOGLE_CLOUD_LOCATION}
spring.ai.google.genai.location=global
spring.ai.google.genai.chat.options.model=gemini-3.1-pro-preview

